image: python:3.8.10
pipelines:
    branches:
        cym-ui:
            - step:
                  deployment: IQ-D1
                  script:
                      - apt-get update
                      - apt-get install -y zip
                      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                      - unzip awscliv2.zip
                      - ./aws/install
                      - pip install aws-sam-cli
                      - python3 -m pip install --upgrade pip
                      - aws configure --profile deployment set aws_access_key_id ${AWS_ACCESS_KEY_ID}
                      - aws configure --profile deployment set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
                      - ssm_schema_uri=$(aws ssm get-parameter --name "/${Env}/api/Url/GetSchema" --query "Parameter.Value" --output text)
                      - ssm_explorer_uri=$(aws ssm get-parameter --name "/${Env}/api/Url/Explorer" --query "Parameter.Value" --output text)
                      - ssm_convert_to_schema_uri=$(aws ssm get-parameter --name "/${Env}/api/Url/ConvertToSchema" --query "Parameter.Value" --output text)
                      - sed -i "s|\"schema_uri\": \"ssm\"|\"schema_uri\": \"$ssm_schema_uri\"|" config.json
                      - sed -i "s|\"explorer_uri\": \"ssm\"|\"explorer_uri\": \"$ssm_explorer_uri\"|" config.json
                      - sed -i "s|\"convert_to_schema_uri\": \"ssm\"|\"convert_to_schema_uri\": \"$ssm_convert_to_schema_uri\"|" config.json
                      - cat config.json
                      - zip -r angular.zip .
                      - aws s3 --region $AWS_DEFAULT_REGION cp angular.zip s3://$AWS_Bucket
                      - aws ssm delete-parameter --region $AWS_DEFAULT_REGION --name /$Env/Cymonix/FusionCentre/version
                      - aws ssm delete-parameter --region $AWS_DEFAULT_REGION --name /$Env/Cymonix/ssr/version
                      - echo $BITBUCKET_BUILD_NUMBER
                      - aws ssm put-parameter --region $AWS_DEFAULT_REGION --name /$Env/cymonix/fusioncentre/version --value 1.0.$BITBUCKET_BUILD_NUMBER --type String --overwrite
                      - aws ssm put-parameter --region $AWS_DEFAULT_REGION --name /$Env/cymonix/ssr/version --value 1.0.$BITBUCKET_BUILD_NUMBER --type String --overwrite
