image: python:3.8.10
pipelines:
    branches:
        cym-ui:
            - step:
                  deployment: IQ-D1
                  script:
                      - apt-get update
                      - apt-get install -y zip
                      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                      - unzip awscliv2.zip
                      - ./aws/install
                      - pip install aws-sam-cli
                      - python3 -m pip install --upgrade pip
                      - aws configure --profile deployment set aws_access_key_id ${AWS_ACCESS_KEY_ID}
                      - aws configure --profile deployment set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
                      - zip -r angular.zip .
                      - aws s3 --region $AWS_DEFAULT_REGION cp angular.zip s3://$AWS_Bucket