version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        BUILD_FOLDER: "dist"
phases:
  install:
    commands:
        - n 14.20
        - echo Installing source NPM dependencies...
        - npm install -g @angular/cli
        - npm install

  build:
    commands:
        - echo Build started 
        - ng build
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes