version: 0.2

env:
    variables:
        BUILD_ENV : "development"
phases:
  install:
    commands:
        - export NODE_OPTIONS=--max-old-space-size=32768
        - n 16.16.0
        - echo Installing source NPM dependencies...
        - npm install -g @angular/cli
        - npm install

  build:
    commands:
        - echo Build started 
        - ng build --verbose # --aot --output-hashing=none
        
  post_build:
    commands:
        # Clear S3 bucket
        - aws s3 rm s3://fusioncenterui --recursive
        - echo S3 bucket is cleared.
        # Copy dist folder to S3 bucket, As ofAngular 7, builds are stored inside an app folder in distribution and not at the root of the dist folder
        - aws s3 cp dist s3://fusioncenterui --recursive --cache-control max-age=60
        - echo Build completed on `date`
        - dir
artifacts:
    files:
        - '**/*'
    discard-paths: yes
    base-directory: 'dist/*'
    
    