export const toolbar = [{
  "name": "Cymonix",
  "url": "../../../../assets/image/Logo2.png",
  "position": "top",
  "type": "image",
  "sector": "1",
  "height": "25",
  "width": "85"
}, {
  "name": "Dashboard",
  "position": "top",
  "type": "string",
  "sector": "2"
},
  {
    "name": "Workspace",
    "position": "top",
    "type": "string",
    "sector": "2"
  }, {
    "name": "Search",
    "position": "top",
    "type": "searchBox",
    "sector": "3"
  }, {
    "name": "Cancel",
    "position": "bottom",
    "type": "button",
    "class": "grey-button",
    "sector": "2"
  }, {
    "name": "Save",
    "position": "bottom",
    "type": "button",
    "class": "solid-button",
    "sector": "2"
  },
  {
    "url": "../../../../assets/image/eye.svg",
    "position": "top",
    "type": "image",
    "sector": "4",
    "height": "15",
    "width": "20"
  }, {
    "url": "../../../../assets/image/chat.svg",
    "position": "top",
    "type": "image",
    "sector": "4",
    "height": "15",
    "width": "20"
  }, {
    "url": "../../../../assets/image/marketplace.svg",
    "position": "top",
    "type": "image",
    "sector": "4",
    "height": "15",
    "width": "20"
  }, {
    "url": "../../../../assets/image/notifications.svg",
    "position": "top",
    "type": "image",
    "sector": "4",
    "height": "15",
    "width": "20"
  }, {
    "url": "../../../../assets/image/settings.svg",
    "position": "top",
    "type": "image",
    "sector": "4",
    "height": "15",
    "width": "20"
  }, {
    "url": "../../../../assets/image/user.svg",
    "position": "top",
    "type": "image",
    "sector": "4",
    "height": "15",
    "width": "20"
  }, {
    "url": "../../../../assets/image/moreIcon2.svg",
    "position": "top",
    "type": "image",
    "sector": "4",
    "height": "15",
    "width": "20"
  },

]
