import {ShapeNodeShape} from "yfiles";

export const GraphTools = [{
  toolName: 'save',
  icon: 'assets/image/save.svg',
  height: 20, width: 20

}, {
  toolName: 'load',
  icon: 'assets/image/refresh.svg',
  height: 20, width: 20
}, {
  toolName: 'zoomIn',
  icon: 'assets/image/zoomIn.svg',
  height: 20, width: 20
}, {
  toolName: 'zoomOut',
  icon: 'assets/image/zoomOut.svg',
  height: 20, width: 20
}, {
  toolName: 'undo',
  icon: 'assets/image/undo.svg',
  height: 15, width: 15
}, {
  toolName: 'redo',
  icon: 'assets/image/redo.svg',
  height: 15, width: 15
},
  {
    toolName: 'fit',
    icon: 'assets/image/fullscreen.svg',
    height: 15, width: 15
  }, {
    toolName: 'cut',
    icon: 'assets/image/cut.svg',
    height: 15, width: 15
  }, {
    toolName: 'copy',
    icon: 'assets/image/copy.svg',
    height: 15, width: 15
  }, {
    toolName: 'paste',
    icon: 'assets/image/paste.svg',
    height: 15, width: 15

  }

]


export const Shapes = [ShapeNodeShape.ROUND_RECTANGLE, ShapeNodeShape.ELLIPSE, ShapeNodeShape.RECTANGLE,
  ShapeNodeShape.DIAMOND, ShapeNodeShape.FAT_ARROW, ShapeNodeShape.FAT_ARROW2, ShapeNodeShape.HEXAGON,
  ShapeNodeShape.HEXAGON2, ShapeNodeShape.TRIANGLE, ShapeNodeShape.TRIANGLE2, ShapeNodeShape.SHEARED_RECTANGLE,
  ShapeNodeShape.SHEARED_RECTANGLE2, ShapeNodeShape.TRAPEZ, ShapeNodeShape.TRAPEZ2, ShapeNodeShape.OCTAGON,
  ShapeNodeShape.STAR5, ShapeNodeShape.STAR6, ShapeNodeShape.STAR8, ShapeNodeShape.STAR5_UP, ShapeNodeShape.PILL]

export const Business = [
  'assets/image/dragdropImage/business/Asset 1.svg',
  'assets/image/dragdropImage/business/Asset 2.svg',
  'assets/image/dragdropImage/business/Asset 3.svg',
  'assets/image/dragdropImage/business/Asset 4.svg',
  'assets/image/dragdropImage/business/Asset 5.svg',
  'assets/image/dragdropImage/business/Asset 6.svg',
  'assets/image/dragdropImage/business/Asset 7.svg',
  'assets/image/dragdropImage/business/Asset 8.svg',
  'assets/image/dragdropImage/business/Asset 9.svg',
  'assets/image/dragdropImage/business/Asset 10.svg',
  'assets/image/dragdropImage/business/Asset 11.svg',
  'assets/image/dragdropImage/business/Asset 12.svg',
  'assets/image/dragdropImage/business/Asset 14.svg',
  'assets/image/dragdropImage/business/Asset 15.svg',
  'assets/image/dragdropImage/business/Asset 16.svg',
  'assets/image/dragdropImage/business/Asset 17.svg',
  'assets/image/dragdropImage/business/Asset 18.svg',
  'assets/image/dragdropImage/business/Asset 19.svg',
  'assets/image/dragdropImage/business/Asset 20.svg',
  'assets/image/dragdropImage/business/Asset 21.svg',
  'assets/image/dragdropImage/business/Asset 22.svg',
  'assets/image/dragdropImage/business/Asset 23.svg',
  'assets/image/dragdropImage/business/Asset 26.svg',
  'assets/image/dragdropImage/business/Asset 27.svg',
  'assets/image/dragdropImage/business/Asset 28.svg',
  'assets/image/dragdropImage/business/Asset 29.svg',
  'assets/image/dragdropImage/business/Asset 30.svg',
  'assets/image/dragdropImage/business/Asset 31.svg',
  'assets/image/dragdropImage/business/Asset 32.svg',
  'assets/image/dragdropImage/business/Asset 34.svg',
  'assets/image/dragdropImage/business/Asset 35.svg',
  'assets/image/dragdropImage/business/Asset 36.svg',
  'assets/image/dragdropImage/business/Asset 37.svg',
  'assets/image/dragdropImage/business/Asset 38.svg',
  'assets/image/dragdropImage/business/Asset 39.svg',
  'assets/image/dragdropImage/business/Asset 40.svg',
  'assets/image/dragdropImage/business/Asset 43.svg',
  'assets/image/dragdropImage/business/Asset 44.svg',
  'assets/image/dragdropImage/business/Asset 45.svg',
  'assets/image/dragdropImage/business/Asset 46.svg',
  'assets/image/dragdropImage/business/Asset 47.svg',
  'assets/image/dragdropImage/business/Asset 48.svg',
  'assets/image/dragdropImage/business/Asset 49.svg',
  'assets/image/dragdropImage/business/Asset 52.svg',
  'assets/image/dragdropImage/business/Asset 53.svg',
  'assets/image/dragdropImage/business/Asset 54.svg',
  'assets/image/dragdropImage/business/Asset 55.svg',
  'assets/image/dragdropImage/business/Asset 56.svg',
  'assets/image/dragdropImage/business/Asset 57.svg',
  'assets/image/dragdropImage/business/Asset 58.svg',
  'assets/image/dragdropImage/business/Asset 59.svg',
  'assets/image/dragdropImage/business/Asset 60.svg',
  'assets/image/dragdropImage/business/Asset 61.svg',
  'assets/image/dragdropImage/business/Asset 62.svg',
  'assets/image/dragdropImage/business/Asset 63.svg',
  'assets/image/dragdropImage/business/Asset 64.svg',
  'assets/image/dragdropImage/business/Asset 65.svg',
  'assets/image/dragdropImage/business/Asset 66.svg',
  'assets/image/dragdropImage/business/Asset 67.svg',
  'assets/image/dragdropImage/business/Asset 68.svg',
  'assets/image/dragdropImage/business/Asset 69.svg',
  'assets/image/dragdropImage/business/Asset 70.svg',
  'assets/image/dragdropImage/business/Asset 71.svg',
  'assets/image/dragdropImage/business/Asset 72.svg',
  'assets/image/dragdropImage/business/Asset 73.svg',
  'assets/image/dragdropImage/business/Asset 74.svg',
  'assets/image/dragdropImage/business/Asset 75.svg',
  'assets/image/dragdropImage/business/Asset 76.svg',
  'assets/image/dragdropImage/business/Asset 77.svg',
  'assets/image/dragdropImage/business/Asset 78.svg']
export const Vehicle = [
  'assets/image/dragdropImage/vehicle/vehicle (1).svg',
  'assets/image/dragdropImage/vehicle/vehicle (2).svg',
  'assets/image/dragdropImage/vehicle/vehicle (3).svg',
  'assets/image/dragdropImage/vehicle/vehicle (4).svg',
  'assets/image/dragdropImage/vehicle/vehicle (5).svg',
  'assets/image/dragdropImage/vehicle/vehicle (6).svg',
  'assets/image/dragdropImage/vehicle/vehicle (7).svg',
  'assets/image/dragdropImage/vehicle/vehicle (8).svg',
  'assets/image/dragdropImage/vehicle/vehicle (9).svg',
  'assets/image/dragdropImage/vehicle/vehicle (10).svg',
  'assets/image/dragdropImage/vehicle/vehicle (11).svg',
  'assets/image/dragdropImage/vehicle/vehicle (12).svg',
  'assets/image/dragdropImage/vehicle/vehicle (13).svg',
  'assets/image/dragdropImage/vehicle/vehicle (14).svg',
  'assets/image/dragdropImage/vehicle/vehicle (15).svg',
  'assets/image/dragdropImage/vehicle/vehicle (16).svg',
  'assets/image/dragdropImage/vehicle/vehicle (17).svg',
  'assets/image/dragdropImage/vehicle/vehicle (18).svg',
  'assets/image/dragdropImage/vehicle/vehicle (19).svg',
  'assets/image/dragdropImage/vehicle/vehicle (20).svg',
  'assets/image/dragdropImage/vehicle/vehicle (21).svg',
  'assets/image/dragdropImage/vehicle/vehicle (22).svg',
  'assets/image/dragdropImage/vehicle/vehicle (23).svg',
  'assets/image/dragdropImage/vehicle/vehicle (24).svg',
  'assets/image/dragdropImage/vehicle/vehicle (25).svg',
  'assets/image/dragdropImage/vehicle/vehicle (26).svg',
  'assets/image/dragdropImage/vehicle/vehicle (27).svg',
  'assets/image/dragdropImage/vehicle/vehicle (28).svg',
  'assets/image/dragdropImage/vehicle/vehicle (29).svg',
  'assets/image/dragdropImage/vehicle/vehicle (31).svg',
  'assets/image/dragdropImage/vehicle/vehicle (32).svg',
  'assets/image/dragdropImage/vehicle/vehicle (33).svg',
  'assets/image/dragdropImage/vehicle/vehicle (34).svg',
  'assets/image/dragdropImage/vehicle/vehicle (35).svg',
  'assets/image/dragdropImage/vehicle/vehicle (36).svg',
  'assets/image/dragdropImage/vehicle/vehicle (37).svg',
  'assets/image/dragdropImage/vehicle/vehicle (38).svg',
  'assets/image/dragdropImage/vehicle/vehicle (39).svg',
  'assets/image/dragdropImage/vehicle/vehicle (40).svg',
  'assets/image/dragdropImage/vehicle/vehicle (41).svg',
  'assets/image/dragdropImage/vehicle/vehicle (42).svg',
  'assets/image/dragdropImage/vehicle/vehicle (43).svg',
  'assets/image/dragdropImage/vehicle/vehicle (44).svg',
  'assets/image/dragdropImage/vehicle/vehicle (45).svg',
  'assets/image/dragdropImage/vehicle/vehicle (46).svg',
  'assets/image/dragdropImage/vehicle/vehicle (47).svg',
  'assets/image/dragdropImage/vehicle/vehicle (48).svg',
  'assets/image/dragdropImage/vehicle/vehicle (49).svg',
  'assets/image/dragdropImage/vehicle/vehicle (50).svg',
  'assets/image/dragdropImage/vehicle/vehicle (51).svg',
  'assets/image/dragdropImage/vehicle/vehicle (52).svg',
  'assets/image/dragdropImage/vehicle/vehicle (53).svg',
  'assets/image/dragdropImage/vehicle/vehicle (54).svg',
  'assets/image/dragdropImage/vehicle/vehicle (55).svg',
  'assets/image/dragdropImage/vehicle/vehicle (56).svg',
  'assets/image/dragdropImage/vehicle/vehicle (57).svg',
  'assets/image/dragdropImage/vehicle/vehicle (58).svg',
  'assets/image/dragdropImage/vehicle/vehicle (59).svg',
  'assets/image/dragdropImage/vehicle/vehicle (60).svg',
  'assets/image/dragdropImage/vehicle/vehicle (61).svg',
  'assets/image/dragdropImage/vehicle/vehicle (62).svg',

];
export const Finance = [
  'assets/image/dragdropImage/finance/finance (1).svg',
  'assets/image/dragdropImage/finance/finance (2).svg',
  'assets/image/dragdropImage/finance/finance (3).svg',
  'assets/image/dragdropImage/finance/finance (4).svg',
  'assets/image/dragdropImage/finance/finance (5).svg',
  'assets/image/dragdropImage/finance/finance (6).svg',
  'assets/image/dragdropImage/finance/finance (7).svg',
  'assets/image/dragdropImage/finance/finance (8).svg',
  'assets/image/dragdropImage/finance/finance (9).svg',
  'assets/image/dragdropImage/finance/finance (10).svg',
  'assets/image/dragdropImage/finance/finance (11).svg',
  'assets/image/dragdropImage/finance/finance (12).svg',
  'assets/image/dragdropImage/finance/finance (13).svg',
  'assets/image/dragdropImage/finance/finance (14).svg',
  'assets/image/dragdropImage/finance/finance (15).svg',
  'assets/image/dragdropImage/finance/finance (16).svg',
  'assets/image/dragdropImage/finance/finance (17).svg',
  'assets/image/dragdropImage/finance/finance (18).svg',
  'assets/image/dragdropImage/finance/finance (19).svg',
  'assets/image/dragdropImage/finance/finance (20).svg',
  'assets/image/dragdropImage/finance/finance (21).svg',
  'assets/image/dragdropImage/finance/finance (23).svg',
  'assets/image/dragdropImage/finance/finance (24).svg',
  'assets/image/dragdropImage/finance/finance (25).svg',
  'assets/image/dragdropImage/finance/finance (26).svg',
  'assets/image/dragdropImage/finance/finance (27).svg',
  'assets/image/dragdropImage/finance/finance (28).svg',
  'assets/image/dragdropImage/finance/finance (29).svg',
  'assets/image/dragdropImage/finance/finance (30).svg',
  'assets/image/dragdropImage/finance/finance (31).svg',
  'assets/image/dragdropImage/finance/finance (32).svg',
  'assets/image/dragdropImage/finance/finance (33).svg',
  'assets/image/dragdropImage/finance/finance (34).svg',
  'assets/image/dragdropImage/finance/finance (35).svg',
  'assets/image/dragdropImage/finance/finance (36).svg',
  'assets/image/dragdropImage/finance/finance (37).svg',
  'assets/image/dragdropImage/finance/finance (38).svg',
  'assets/image/dragdropImage/finance/finance (39).svg',
  'assets/image/dragdropImage/finance/finance (40).svg',
  'assets/image/dragdropImage/finance/finance (41).svg',
  'assets/image/dragdropImage/finance/finance (42).svg',
  'assets/image/dragdropImage/finance/finance (43).svg',
  'assets/image/dragdropImage/finance/finance (44).svg',
  'assets/image/dragdropImage/finance/finance (45).svg',
  'assets/image/dragdropImage/finance/finance (46).svg',
  'assets/image/dragdropImage/finance/finance (47).svg',
  'assets/image/dragdropImage/finance/finance (48).svg',
  'assets/image/dragdropImage/finance/finance (49).svg',
];
export const Automotive = [
  'assets/image/dragdropImage/automotive/automotive (1).svg',
  'assets/image/dragdropImage/automotive/automotive (2).svg',
  'assets/image/dragdropImage/automotive/automotive (3).svg',
  'assets/image/dragdropImage/automotive/automotive (4).svg',
  'assets/image/dragdropImage/automotive/automotive (5).svg',
  'assets/image/dragdropImage/automotive/automotive (6).svg',
  'assets/image/dragdropImage/automotive/automotive (7).svg',
  'assets/image/dragdropImage/automotive/automotive (8).svg',
  'assets/image/dragdropImage/automotive/automotive (9).svg',
  'assets/image/dragdropImage/automotive/automotive (10).svg',
  'assets/image/dragdropImage/automotive/automotive (11).svg',
  'assets/image/dragdropImage/automotive/automotive (12).svg',
  'assets/image/dragdropImage/automotive/automotive (13).svg',
  'assets/image/dragdropImage/automotive/automotive (14).svg',
  'assets/image/dragdropImage/automotive/automotive (15).svg',
  'assets/image/dragdropImage/automotive/automotive (16).svg',
  'assets/image/dragdropImage/automotive/automotive (17).svg',
  'assets/image/dragdropImage/automotive/automotive (18).svg',
  'assets/image/dragdropImage/automotive/automotive (19).svg',
  'assets/image/dragdropImage/automotive/automotive (20).svg',
  'assets/image/dragdropImage/automotive/automotive (21).svg',
  'assets/image/dragdropImage/automotive/automotive (22).svg',
  'assets/image/dragdropImage/automotive/automotive (23).svg',
  'assets/image/dragdropImage/automotive/automotive (24).svg',
  'assets/image/dragdropImage/automotive/automotive (25).svg',
  'assets/image/dragdropImage/automotive/automotive (26).svg',
  'assets/image/dragdropImage/automotive/automotive (27).svg',

];

export const FileImg = [
  'assets/image/dragdropImage/files/files (1).svg',
  'assets/image/dragdropImage/files/files (2).svg',
  'assets/image/dragdropImage/files/files (3).svg',
  'assets/image/dragdropImage/files/files (4).svg',
  'assets/image/dragdropImage/files/files (5).svg',
  'assets/image/dragdropImage/files/files (6).svg',
  'assets/image/dragdropImage/files/files (7).svg',
  'assets/image/dragdropImage/files/files (8).svg',
  'assets/image/dragdropImage/files/files (9).svg',
  'assets/image/dragdropImage/files/files (10).svg',
  'assets/image/dragdropImage/files/files (11).svg',
  'assets/image/dragdropImage/files/files (12).svg',
  'assets/image/dragdropImage/files/files (13).svg',
  'assets/image/dragdropImage/files/files (14).svg',
  'assets/image/dragdropImage/files/files (15).svg',
  'assets/image/dragdropImage/files/files (16).svg',
  'assets/image/dragdropImage/files/files (17).svg',
  'assets/image/dragdropImage/files/files (18).svg',
  'assets/image/dragdropImage/files/files (19).svg',
  'assets/image/dragdropImage/files/files (20).svg',
  'assets/image/dragdropImage/files/files (21).svg',
  'assets/image/dragdropImage/files/files (22).svg',
  'assets/image/dragdropImage/files/files (23).svg',
  'assets/image/dragdropImage/files/files (24).svg',
  'assets/image/dragdropImage/files/files (25).svg',
  'assets/image/dragdropImage/files/files (26).svg',
  'assets/image/dragdropImage/files/files (27).svg',
  'assets/image/dragdropImage/files/files (28).svg',
  'assets/image/dragdropImage/files/files (29).svg',
  'assets/image/dragdropImage/files/files (30).svg',
  'assets/image/dragdropImage/files/files (31).svg',
  'assets/image/dragdropImage/files/files (32).svg',
  'assets/image/dragdropImage/files/files (33).svg',
  'assets/image/dragdropImage/files/files (34).svg',
  'assets/image/dragdropImage/files/files (35).svg',
  'assets/image/dragdropImage/files/files (36).svg',
  'assets/image/dragdropImage/files/files (37).svg',
  'assets/image/dragdropImage/files/files (38).svg',
  'assets/image/dragdropImage/files/files (39).svg',
  'assets/image/dragdropImage/files/files (40).svg',
  'assets/image/dragdropImage/files/files (41).svg',
  'assets/image/dragdropImage/files/files (42).svg',
  'assets/image/dragdropImage/files/files (43).svg',
  'assets/image/dragdropImage/files/files (44).svg',
  'assets/image/dragdropImage/files/files (45).svg',
  'assets/image/dragdropImage/files/files (46).svg',
  'assets/image/dragdropImage/files/files (47).svg',
  'assets/image/dragdropImage/files/files (48).svg',
  'assets/image/dragdropImage/files/files (49).svg',
  'assets/image/dragdropImage/files/files (50).svg',


];
export const People = [
  'assets/image/dragdropImage/people/people (1).svg',
  'assets/image/dragdropImage/people/people (2).svg',
  'assets/image/dragdropImage/people/people (3).svg',
  'assets/image/dragdropImage/people/people (4).svg',
  'assets/image/dragdropImage/people/people (5).svg',
  'assets/image/dragdropImage/people/people (6).svg',
  'assets/image/dragdropImage/people/people (7).svg',
  'assets/image/dragdropImage/people/people (8).svg',
  'assets/image/dragdropImage/people/people (9).svg',
  'assets/image/dragdropImage/people/people (10).svg',
  'assets/image/dragdropImage/people/people (11).svg',
  'assets/image/dragdropImage/people/people (12).svg',
  'assets/image/dragdropImage/people/people (13).svg',
  'assets/image/dragdropImage/people/people (14).svg',
  'assets/image/dragdropImage/people/people (15).svg',
  'assets/image/dragdropImage/people/people (16).svg',
  'assets/image/dragdropImage/people/people (17).svg',
  'assets/image/dragdropImage/people/people (18).svg',
  'assets/image/dragdropImage/people/people (19).svg',
  'assets/image/dragdropImage/people/people (20).svg',
  'assets/image/dragdropImage/people/people (21).svg',
  'assets/image/dragdropImage/people/people (23).svg',
  'assets/image/dragdropImage/people/people (24).svg',
  'assets/image/dragdropImage/people/people (25).svg',
  'assets/image/dragdropImage/people/people (26).svg',
  'assets/image/dragdropImage/people/people (27).svg',
  'assets/image/dragdropImage/people/people (28).svg',
  'assets/image/dragdropImage/people/people (29).svg',
  'assets/image/dragdropImage/people/people (30).svg',
  'assets/image/dragdropImage/people/people (31).svg',
  'assets/image/dragdropImage/people/people (32).svg',
  'assets/image/dragdropImage/people/people (34).svg',
  'assets/image/dragdropImage/people/people (35).svg',
  'assets/image/dragdropImage/people/people (36).svg',
  'assets/image/dragdropImage/people/people (37).svg',
  'assets/image/dragdropImage/people/people (38).svg',
  'assets/image/dragdropImage/people/people (39).svg',
  'assets/image/dragdropImage/people/people (40).svg',
  'assets/image/dragdropImage/people/people (41).svg',
  'assets/image/dragdropImage/people/people (42).svg',
  'assets/image/dragdropImage/people/people (43).svg',
  'assets/image/dragdropImage/people/people (44).svg',
  'assets/image/dragdropImage/people/people (45).svg',
  'assets/image/dragdropImage/people/people (46).svg',
  'assets/image/dragdropImage/people/people (47).svg',
  'assets/image/dragdropImage/people/people (48).svg',
  'assets/image/dragdropImage/people/people (49).svg',
  'assets/image/dragdropImage/people/people (50).svg',
  'assets/image/dragdropImage/people/people (51).svg',
  'assets/image/dragdropImage/people/people (53).svg',
  'assets/image/dragdropImage/people/people (54).svg',
  'assets/image/dragdropImage/people/people (55).svg',
  'assets/image/dragdropImage/people/people (56).svg',
  'assets/image/dragdropImage/people/people (57).svg',
  'assets/image/dragdropImage/people/people (58).svg',

];
export const Social = [
  'assets/image/dragdropImage/social/social (1).svg',
  'assets/image/dragdropImage/social/social (2).svg',
  'assets/image/dragdropImage/social/social (3).svg',
  'assets/image/dragdropImage/social/social (4).svg',
  'assets/image/dragdropImage/social/social (5).svg',
  'assets/image/dragdropImage/social/social (6).svg',
  'assets/image/dragdropImage/social/social (7).svg',
  'assets/image/dragdropImage/social/social (8).svg',
  'assets/image/dragdropImage/social/social (8).svg',
  'assets/image/dragdropImage/social/social (9).svg',
  'assets/image/dragdropImage/social/social (10).svg',
  'assets/image/dragdropImage/social/social (11).svg',
  'assets/image/dragdropImage/social/social (12).svg',
  'assets/image/dragdropImage/social/social (13).svg',
  'assets/image/dragdropImage/social/social (14).svg',
  'assets/image/dragdropImage/social/social (15).svg',
  'assets/image/dragdropImage/social/social (16).svg',
  'assets/image/dragdropImage/social/social (17).svg',
  'assets/image/dragdropImage/social/social (18).svg',
  'assets/image/dragdropImage/social/social (19).svg',
  'assets/image/dragdropImage/social/social (20).svg',
  'assets/image/dragdropImage/social/social (21).svg',
  'assets/image/dragdropImage/social/social (22).svg',
  'assets/image/dragdropImage/social/social (23).svg',
  'assets/image/dragdropImage/social/social (24).svg',
  'assets/image/dragdropImage/social/social (25).svg',
  'assets/image/dragdropImage/social/social (26).svg',
  'assets/image/dragdropImage/social/social (27).svg',
  'assets/image/dragdropImage/social/social (28).svg',
  'assets/image/dragdropImage/social/social (29).svg',
  'assets/image/dragdropImage/social/social (30).svg',
  'assets/image/dragdropImage/social/social (31).svg',
  'assets/image/dragdropImage/social/social (32).svg',
  'assets/image/dragdropImage/social/social (33).svg',
  'assets/image/dragdropImage/social/social (34).svg',
  'assets/image/dragdropImage/social/social (35).svg',
  'assets/image/dragdropImage/social/social (36).svg',
  'assets/image/dragdropImage/social/social (37).svg',
  'assets/image/dragdropImage/social/social (38).svg',
  'assets/image/dragdropImage/social/social (39).svg',
  'assets/image/dragdropImage/social/social (40).svg',
  'assets/image/dragdropImage/social/social (41).svg',
  'assets/image/dragdropImage/social/social (42).svg',
  'assets/image/dragdropImage/social/social (43).svg',
  'assets/image/dragdropImage/social/social (44).svg',
  'assets/image/dragdropImage/social/social (45).svg',
  'assets/image/dragdropImage/social/social (46).svg',
  'assets/image/dragdropImage/social/social (47).svg',
  'assets/image/dragdropImage/social/social (48).svg',
  'assets/image/dragdropImage/social/social (49).svg',
  'assets/image/dragdropImage/social/social (50).svg',

];

export const Network = [
  'assets/image/dragdropImage/network/network (1).svg',
  'assets/image/dragdropImage/network/network (2).svg',
  'assets/image/dragdropImage/network/network (3).svg',
  'assets/image/dragdropImage/network/network (4).svg',
  'assets/image/dragdropImage/network/network (5).svg',
  'assets/image/dragdropImage/network/network (6).svg',
  'assets/image/dragdropImage/network/network (7).svg',
  'assets/image/dragdropImage/network/network (8).svg',
  'assets/image/dragdropImage/network/network (9).svg',
  'assets/image/dragdropImage/network/network (10).svg',
  'assets/image/dragdropImage/network/network (11).svg',
  'assets/image/dragdropImage/network/network (12).svg',
  'assets/image/dragdropImage/network/network (13).svg',
  'assets/image/dragdropImage/network/network (14).svg',
  'assets/image/dragdropImage/network/network (15).svg',
  'assets/image/dragdropImage/network/network (16).svg',
  'assets/image/dragdropImage/network/network (17).svg',
  'assets/image/dragdropImage/network/network (18).svg',
  'assets/image/dragdropImage/network/network (19).svg',
  'assets/image/dragdropImage/network/network (20).svg',
  'assets/image/dragdropImage/network/network (21).svg',
  'assets/image/dragdropImage/network/network (22).svg',
  'assets/image/dragdropImage/network/network (23).svg',
  'assets/image/dragdropImage/network/network (24).svg',
  'assets/image/dragdropImage/network/network (25).svg',
  'assets/image/dragdropImage/network/network (26).svg',
  'assets/image/dragdropImage/network/network (27).svg',
  'assets/image/dragdropImage/network/network (28).svg',
  'assets/image/dragdropImage/network/network (29).svg',
  'assets/image/dragdropImage/network/network (30).svg',
  'assets/image/dragdropImage/network/network (31).svg',
  'assets/image/dragdropImage/network/network (32).svg',
  'assets/image/dragdropImage/network/network (33).svg',
  'assets/image/dragdropImage/network/network (34).svg',
  'assets/image/dragdropImage/network/network (35).svg',
  'assets/image/dragdropImage/network/network (36).svg',
  'assets/image/dragdropImage/network/network (37).svg',
  'assets/image/dragdropImage/network/network (38).svg',
  'assets/image/dragdropImage/network/network (39).svg',
  'assets/image/dragdropImage/network/network (40).svg',
  'assets/image/dragdropImage/network/network (41).svg',
  'assets/image/dragdropImage/network/network (42).svg',
  'assets/image/dragdropImage/network/network (43).svg',
  'assets/image/dragdropImage/network/network (44).svg',
  'assets/image/dragdropImage/network/network (45).svg',
  'assets/image/dragdropImage/network/network (46).svg',
  'assets/image/dragdropImage/network/network (47).svg',
  'assets/image/dragdropImage/network/network (48).svg',
  'assets/image/dragdropImage/network/network (49).svg',
  'assets/image/dragdropImage/network/network (50).svg'
];
